# Generated by Django 4.1.3 on 2022-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='to_date',
            field=models.DateField(),
        ),
    ]
