# Generated by Django 4.1.3 on 2022-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0002_alter_hotelbooking_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
