# Generated by Django 4.1.3 on 2022-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0003_hotelbooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='order_id',
            field=models.CharField(default='IDHO00RAA', max_length=1000),
        ),
    ]
