# Generated by Django 4.1.3 on 2022-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0004_hotelbooking_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='order_id',
            field=models.CharField(default='noid', max_length=1000),
        ),
    ]
