# Generated by Django 4.1.3 on 2022-11-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0005_alter_hotelbooking_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_id',
            field=models.CharField(default='noid', max_length=100),
        ),
    ]
