# Generated by Django 4.1.3 on 2022-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0007_hotelbooking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
