# Generated by Django 4.1.3 on 2022-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hote_region',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Delhi', 'Delhi'), ('Vishakhapatnam', 'Vishakhapatnam'), ('Bengaluru', 'Bengaluru'), ('Lucknow', 'Lucknow'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Goa', 'Goa'), ('Srinagar', 'Srinagar')], default='Hyderabad', max_length=100),
        ),
    ]
