# Generated by Django 4.1.3 on 2022-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_hote_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hote_name',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hote_region',
            new_name='hotel_region',
        ),
    ]
